version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: gitlab-poller-postgres
    environment:
      POSTGRES_DB: agent8_dev
      POSTGRES_USER: agent8
      POSTGRES_PASSWORD: dev_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agent8 -d agent8_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
